### ISSUE TITLE
CDTReplicatorFactory initWithDatastoreManager:nil returns a non-nil object

### ISSUE THREAD

**Issue by jimix** [cloudant/CDTDatastore#132]
If you call:
```objc
CDTReplicatorFactory *repFactory = [[CDTReplicatorFactory alloc] initWithDatastoreManager:nil];
```
The result is a non-nil object that can then be used to create a `CDTReplicator` that is non-nil but is essentially useless when you try to use it.

**Comment by rhyshort** [comment]
I've opened an ticket in our internal issue tracker, we will update this ticket as progress is made
