### ISSUE TITLE
Creating a cordova plugin for CDTDatastore

### ISSUE THREAD

**Issue by eforth** [cloudant/CDTDatastore#154]
I notice that you are using cocapods for dependency management. Is it possible to create a cordova plugin for CDTDatastore without using cocapods?

**Comment by mikerhodes** [comment]
I'm not quite sure what you are asking -- could you elaborate a little on your question?

Thanks!

**Comment by eforth** [comment]
I would like to create a cordova plugin for Cloudant Sync but my issue regarding the iOS version is that "CDTDatastore" uses cocapods a third party tool to handle dependency management. Is there a way to use "CDTDatastore" with cocopods?

**Comment by mikerhodes** [comment]
Ah, I see. I've heard that it is difficult to combine Cocoapods and Cordova together.

Right now we don't have a supported way to build a standalone framework unfortunately. It is possible, we've done one-offs of dynamic frameworks for iOS 8 but we don't have a process to reliably create them.

At some point in the medium term, I'd like to get us working with https://github.com/Carthage/Carthage to get framework building more easily, but for now I'm guessing you'd need to run `pod install` to get the library into the cordova app, then use the plugin from there :-/

**Comment by surajpandey-anz** [comment]
May I ask if that 'one-offs' dynamic frameworks for iOS 8 could be shared with the 'banking' client I mentioned in slack? 

A recap: The bank is looking at a cordova plugin for Cloudant Sync, that is IBM supported.

**Comment by rhyshort** [comment]
There is a newly released Cordova plug-in which uses CDTDatastore, see https://github.com/cloudant/sync-cordova-plugin

**Comment by mnewmedia** [comment]
Woooow super crazy fucking cool, just freaking out! 🎉 I love you all :P
