### ISSUE TITLE
DB Not opening

### ISSUE THREAD

**Issue by endikamontejo** [cloudant/CDTDatastore#155]
I am getting pretty often in iOS app the following message when trying to open the db: 
error opening!: 23
Could not create database queue for path /var/mobile/Containers/Data/Application/xxx/dbname.touchdb

Is there any reason why this happens so often? I am using the v0.16 version of CDTDatastore

**Comment by mikerhodes** [comment]
@endikamontejo: I don't think this error should be happening, that sometimes the database can be opened and sometimes not.

How often is "pretty often"? More than half the time, once in every ten tries etc.?

Did this happen in older versions of the library or has it only started happening recently?

**Comment by endikamontejo** [comment]
Hi @mikerhodes . We open the db each time we start the session of the app, so it can be around 1/8 or 1/10 times when we get this problem.

I would like to mark our apps usually have around 20.000 documents, so are quite heavy and also that this error doesn't happen in our Mac app but just in iOS one.

I can't give you a really accurate feedback about when it started happening but I suspect it also happened in 0.15 (but can't ensure it)

**Comment by mikerhodes** [comment]
Do you get any other interesting information if you turn logging on? See [logging.md](https://github.com/cloudant/CDTDatastore/blob/master/doc/logging.md).

**Comment by endikamontejo** [comment]
Sorry for replying so late Mike, I will try it and if I find some info from it will let you know

**Comment by mikerhodes** [comment]
@endikamontejo is it okay for me to close this issue, given it's quite old?

**Comment by endikamontejo** [comment]
Yes, for sure
