### ISSUE TITLE
Implement Continous Replication

### ISSUE THREAD

**Issue by p2k** [cloudant/CDTDatastore#181]
The underlying TDReplicator class seems to already support continuous replication. What needs to be done in order to enable continuous replication in CDTReplicator?

**Comment by mikerhodes** [comment]
Sorry for the late reply. 

Right now this is intentionally disallowed. CouchbaseLite also removed this feature a while back, iirc. It seemed a little too easy to use up cell data allowances and battery time with this.

What was your use-case, can it be solved using push notifications when databases change?

**Comment by p2k** [comment]
I am trying to synchronize changes in my app across the user's devices and several backend services which are listening for changes too. I think with some extra work, it can be achieved with push notifications and scheduled replication intervals just as well.

**Comment by p2k** [comment]
Continous replication would make this trivial and could inspire programmers to implement "live mode" in their apps. One could put two devices next to each other, make changes on the first and see them live, with only a few seconds delay, on the second one. In this case, continuous replication is more efficient than push notifications or polling.

Of course it would be the programmer's responsibility not to drain the batteries or cell data allowances and to warn the user appropriately.

And you are mistaken, [CouchbaseLite still has continuous replication](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLReplication.h). I can find no evidence that this ever got removed nor any people actually complaining about battery or cell data allowances (or maybe I enter the wrong search terms into google).

**Comment by mikerhodes** [comment]
Hmm, you're right -- not sure where I dragged up the continuous thing on CBL from. Sorry about that.

I'll take your thoughts into account on continuous - could be right that we should probably leave the decision up to the developer.

Will close this issue, but made a note :)
