### ISSUE TITLE
Could not build Objective-C module 'CDTDatastore' - Swift

### ISSUE THREAD

**Issue by francistek** [cloudant/CDTDatastore#223]
Hi,
i'm having a problem running my project with CDTDatastore, i'm using Cocoapods and Swift.
When i build the project all goes fine, but when i try to do "import CDTDatastore", Xcode give me a compilation error: "Could not build Objective-C module 'CDTDatastore'", there are others error that are all of the same type, like "Include of non-modular header inside framework module..."
I have some additional information:
- i use Xcode 7.2
- in the Podfile i have "use_frameworks!"
- if i remove "use_frameworks!" and i import "CloudantSync.h" in the bridging header all goes fine, but i  can't remove "use_frameworks!"

**Comment by rhyshort** [comment]
In the current release version of CDTDatastore you cannot build as a framework, in the next release (1.1) this function will be supported, for reference it was fixed as part of #194
