### ISSUE TITLE
Query Nullability Annoations

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#242]
There may be a mistake in the nullability annotations for Query, this line: https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/query/CDTQIndex.m#L100 generates a warning in xcode for passing nil to something that requires a nonnull value.

**Comment by rhyshort** [comment]
and again here: https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/query/CDTQIndexManager.m#L277

**Comment by ricellis** [comment]
See also #296
