### ISSUE TITLE
Remove remaining instances of networking not using `NSURLSession`

### ISSUE THREAD

**Issue by ricellis** [cloudant/CDTDatastore#247]
We need to ensure there is no networking remaining that is not using `NSURLSession` (see  [this](https://developer.apple.com/news/?id=05042016a)).

A cursory search found two instances of `NSURLConnection`:
https://github.com/cloudant/CDTDatastore/blob/c407be82aa0d821628a9b59658e9f32e38344426/CDTDatastore/touchdb/TDMultipartUploader.m#L54

https://github.com/cloudant/CDTDatastore/blob/c407be82aa0d821628a9b59658e9f32e38344426/CDTDatastore/touchdb/TDRemoteRequest.m#L249

**Comment by ricellis** [comment]
@willholley also points out:

>https://github.com/cloudant/CDTDatastore/blob/c407be82aa0d821628a9b59658e9f32e38344426/CDTDatastore/touchdb/TDReachability.h#L12 and
https://github.com/cloudant/CDTDatastore/blob/92dfcd1e6eaa52109200658400f8ea7958091f2a/CDTDatastoreTests/CDTReplicationTests.m#L79 might cause problems

**Comment by willholley** [comment]
that list was from https://developer.apple.com/videos/play/wwdc2015/719/ where they state (9 mins in) that the following will break under IPv6:

   uint32_t
   in_addr
   sockaddr_in
   inet_aton
   gethostbyname
   gethostbyname2(hostname,AF_INET)

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
