### ISSUE TITLE
Replication Acceptance doesn't clean up after itself.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#252]
Replication Acceptance tests do not remove the databases from the remote server, this causes issues when another test expects a clean server instance.

**Comment by ricellis** [comment]
Perhaps this is only true if the tests are terminated from a hang (which they have been prone to in the past)? After a clean run I didn't see any databases remaining.

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
