### ISSUE TITLE
Remove Legacy test cases

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#261]
Legacy Test cases for MYUtilites should be removed, an example of the test cases to be removed can be found [here](https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/vendor/MYUtilities/MYErrorUtils.m#L212).

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
