### ISSUE TITLE
CDTReplicatior state tests in ReplicationAcceptance.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#264]
Add state tests for the following scenarios to ReplicationAcceptance:
- local database is deleted
- remote database is deleted
- loses network connection temporarily
  - for > 60s but < 120s
  - for < 60s
      (the default retry waiting period is 60s)
- loses network connection permanently 
- remote credentials are changed

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
