### ISSUE TITLE
Remove Exposure of TDStatus Errors

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#265]
Exposure of TDStatus errors should be eliminated to do this the following steps should be followed:
1. Use a single error domain across the CDT parts of the library -- CDTDatastoreErrorDomain.
2. Devote a block of 1000 error codes to each subsystem
   (replication, attachments, CRUD, indexing).

This allows the developer to see, for example, 1007 and know it's a CRUD
error, and we can expand the error codes produced by a subsystem (up to
999 codes, anyway).
1. Audit each error site, and decide what the most useful error is, and
   whether it needs a unique code.
2. Wrap TD Errors. 
3. Document all our error codes properly. Using a single domain and
   declaring them a single header.

**Comment by rhyshort** [comment]
It's worth taking note of [SE-0112](https://github.com/apple/swift-evolution/blob/master/proposals/0112-nserror-bridging.md) which will introduce better bridging into swift and a new macro for Objc errors.

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
