### ISSUE TITLE
TDPusher only writes checkpoint document at completion, rather than as batches are written

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#270]
The last sequence value isn't written to the remote checkpoint doc from time-to-time by the push replicator. It only writes the lastSequence value at the end of replication, when TDReplicator -stopped is called. This is okay as long as the replicator exits gracefully. However, if the code crashes completely, then all push replication progress will be lost. 

The push replicator only calls TDReplicator -saveLastSequence once, at the end.  It doesn’t even try during replications. whereas, the pull replicator does make attempts at times during replication.

**Comment by tomblench** [comment]
Is this true? `-removePending` in `TDReplicator` has the following line: 

`self.lastSequence = [NSNumber numberWithUnsignedLongLong:maxCompleted];` 

This calls into `TDPusher`s `-setLastSequence`

**Comment by rhyshort** [comment]
As far as I'm aware, unless `-setLastSequence` calls into `-saveLastSequence` then it is valid, I haven't looked at the code in a while though.

**Comment by rhyshort** [comment]
After checking the code `-setLastSequence` triggers savingof the checkpoint by calling `saveLastSequence` via `performSelector`. I think it's safe to close this out.
