### ISSUE TITLE
Make sure CDTDatastore skips documents with empty ids during replication

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#274]
There was a bug in CouchDB that would allow empty doc ids to be generated, since this is no longer valid, CDTDatastore should skip empty document ids during replication if encountered.

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
