### ISSUE TITLE
Ability to replicate from a specific sequence number

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#280]
Cloudant supports the ability to kick off a replication from a specific sequence number (see the use of since_seq in https://docs.cloudant.com/backup-guide.html#incremental-backups).

In scenarios where filtered replication is used to sync to a mobile device, it is useful to be able to skip existing documents which you know to not be relevant. Adding support for since_seq to our client-side replicator would solve this and match the server-side replication parameters.

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
