### ISSUE TITLE
Validate attachment dict key matches attachment name

### ISSUE THREAD

**Issue by ricellis** [cloudant/CDTDatastore#287]
Attachments are stored in a dict of `{name : att}`, whilst the example code demonstrates using this dict with `{att.name : att}` there is no restriction on doing `{@"otherName" : att}` which gives the impression that the attachment name is "otherName", but in fact will still be whatever `att.name` is. We should enforce the dict key being the same as the attachment name.

**Comment by rhyshort** [comment]
I think there are two parts to this, we can validate and log warnings for 1.x.x and then for 2.x.x we can then error out.

**Comment by rhyshort** [comment]
Merged work to print a warning, when we start working towards 2.0 we can re look at this issue and make it an error.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
