### ISSUE TITLE
Replication history for checkpoint documents

### ISSUE THREAD

**Issue by ricellis** [cloudant/CDTDatastore#288]
During replication, the local and remote checkpoint documents should be compared to make sure the last sequence number contained in each matches before that sequence number is used as the starting point for reading the source database's change feed.

Both documents need to be checked, because otherwise one of the source or target databases my have been changed (e.g., deleted and recreated) in such a way that replication needs to restart before it can be carried out correctly.

This can cause problems if a checkpoint document is only written to one database or the other. Say a local checkpoint document is written, but because a device has gone offline the remote one cannot be written. In this case the local and remote checkpoint documents contain differing last sequence numbers, so the replication starts from 0 in the case of naively comparing just the last sequence numbers in the documents.

CouchDB implements a cleverer algorithm where a history of sequence numbers at replication time are maintained. This means that in the above situation it's possible for the oldest common sequence number to be found and the replication continued from there rather than having to reset completely.
1. Check if the replication code checks for matching sequence numbers in source and target. If not implement that check.
2. Start maintaining history in the checkpoint documents that we write to both ends of the replication process and implement the mechanism to find a latest common version.

**Comment by rhyshort** [comment]
The [CouchDB](http://docs.couchdb.org/en/master/replication/protocol.html#find-common-ancestry) docs describe the algorithm to use, it will require a decent amount of work in the replicator. I'm starting to think that this is another argument to rewrite the replicator stack as a whole.

**Comment by rhyshort** [comment]
Should be done as part of #331. Closing.
