### ISSUE TITLE
Unable to bridge to Swift project

### ISSUE THREAD

**Issue by bluemixgaragelondon** [cloudant/CDTDatastore#300]
I tried to bridge to a swift project via cocoapod:

platform :ios, '8.0'
use_frameworks!

target "CloudantSwiftSyncDemoTest" do
  pod "CDTDatastore"
end

But I am getting this error complaining about existence of a non-module header (see attached image) in one of the dependencies: FMDatabase. Are you planning to replace with one that allow bridging to Swift projects?

![bridging error](https://cloud.githubusercontent.com/assets/12859683/16845717/cd5ddb72-49e1-11e6-8ce4-7c23ff4af79c.png)

**Comment by rhyshort** [comment]
You should be able to use `CDTDatastore` with the `use_frameworks!` option since 1.1.1, please run `pod update` to make sure you have the latest version.

**Comment by bluemixgaragelondon** [comment]
@rhyshort No luck I did as recommended but now it can't find the header file.

![cloudant sync not found](https://cloud.githubusercontent.com/assets/12859683/16847856/efc55e8e-49ea-11e6-8217-f46711ab9ec7.png)

**Comment by rhyshort** [comment]
With it built as a framework, you'll need to do `#import <CDTDatastore/CloudantSync.h>`

**Comment by bluemixgaragelondon** [comment]
@rhyshort Thanks. It's working now.

You might like to update the README.

![screen shot 2016-07-15 at 09 54 57](https://cloud.githubusercontent.com/assets/12859683/16868939/3ed2d8a8-4a72-11e6-959b-e496e08423e6.png)

**Comment by rhyshort** [comment]
Not a problem, thanks for point out the error with the README :)
