### ISSUE TITLE
Some replication acceptance tests fail for small values of `TEST_COUCH_N_DOCS` 

### ISSUE THREAD

**Issue by tomblench** [cloudant/CDTDatastore#304]
These tests rely on replication running for a long enough time before we try to delete the local database. If the replication completes before we delete the local database, it doesn't trigger the condition we are expecting and the test fails (even though nothing has gone wrong).

We need a way of excluding these tests from runs where the number of documents is small. Setting a small number of documents is obviously convenient for quick test runs to check that replication isn't broken.

```
testPullErrorsWhenLocalDatabaseIsDeleted
testPushErrorsWhenLocalDatabaseIsDeleted
testSyncReplicationErrorsWhenLocalDatabaseDeleted_pullDelegateDeletes
testSyncReplicationErrorsWhenLocalDatabaseDeleted_pushDelegateDeletes
```

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
