### ISSUE TITLE
Tests test429Retry and testFiltersWithChangesFeed are failing against iOS 

### ISSUE THREAD

**Issue by emlaver** [cloudant/CDTDatastore#308]
After speaking with @tomblench, it's possible that these tests are failing because the interceptor is not being called.  It's probably best to exclude these tests from running against iOS until the issue can be fixed.

**Comment by tomblench** [comment]
We can't run these tests on iOS because we can't open arbitrary ports there. These tests rely on starting a mini HTTP server so we can't run them on the iOS platform. For now, disabling them on the iOS platform is acceptable
