### ISSUE TITLE
Investigate SQLCipher XCode 8/iOS 10 implications

### ISSUE THREAD

**Issue by ricellis** [cloudant/CDTDatastore#323]
Check and test how we are impacted by the SQLCipher advice in [this post](https://discuss.zetetic.net/t/important-advisory-sqlcipher-with-xcode-8-and-ios-10/1688) and whether changes are needed in the way CDT (or FMDB) links.

**Comment by rhyshort** [comment]
FMDB's podspec links to SQLCipher.https://github.com/ccgus/fmdb/blob/master/FMDB.podspec#L42-L47

Looking through our podspec and that of our deps, we don't call out to SQLite directly. We rely on FMDB to bring it in. 

CocoaLumberjack doesn't bring it in, so I **think** we are ok with regards to this, but I think someone who knows more about this should double check my findings.

**Comment by rhyshort** [comment]
I think something we *could* do to make this easier / better for the user is to implement the suggested check in the post.

extract from post:

```
Runtime SQLCipher Check
In order to avoid situations where SQLite might be used improperly at runtime, we strongly recommend that applications institute a runtime test to ensure that the application is actually using SQLCipher on the active connection. This is very simple to implement, and will incur no performance penalty.

All recent versions of SQLCipher include a pragma called cipher_version. This pragma can be used to determine the version of the library in use. Notably, it will only return a value when run under SQLCipher. Therefore, it can be used as an effective test to check that SQLCipher is in use with the current database connection. Here is a brief example:

BOOL is_sqlcipher = NO;
sqlite3_stmt *stmt;

if(sqlite3_prepare_v2(database, "PRAGMA cipher_version;", -1, &stmt, NULL) == SQLITE_OK) {
  if(sqlite3_step(stmt)== SQLITE_ROW) {
    const unsigned char *ver = sqlite3_column_text(stmt, 0);
    if(ver != NULL) {
      is_sqlcipher = YES;
    }
  }
  sqlite3_finalize(stmt);
}
We strongly recommend that applications use code like this as a failsafe to ensure that SQLCipher is being used at runtime before operating on a database.

```

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
