### ISSUE TITLE
Query doesn't support index directions, but accepts them as the definition

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#332]
CDTQ index definition accepts Sort Syntax for the `fields` to be indexed, however the sort directions are promptly discard see https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/query/CDTQIndexCreator.m#L227-L231.

This should be implemented, and in the meantime, document the limitation if it is not already.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
