### ISSUE TITLE
Re-enable encryption tests

### ISSUE THREAD

**Issue by ricellis** [cloudant/CDTDatastore#339]
The issues with encryption tests exposed by #337 stem from changes made in #215 to build frameworks. Prior to that PR there were two copies of some encryption test files:

* `CDTQIndexManagerEncryptionTests.m`
* `DatastoreEncryptionTests.m`
* `DatastoreManagerEncryptionTests.m`
* `TD_DatabaseEncryptionTests.m`

In the locations:

1. `Tests/Encryption`
1. `EncryptionTests/Encyrption Tests`

There were some common test methods between the files, but each also had unique tests based on whether they were run with (`EncryptionTests/Encyrption Tests`) or without (`Tests/Encryption`) the `SQLCipher` dependency.

We need to re-enable the tests that were removed and if we are not going to use the previous workspace approach come up with some other mechanism of enabling the specific ones needed for each environment.

FYI @rhyshort

**Comment by ricellis** [comment]
1. CDTQIndexManagerEncryptionTests
    * Common
        * testCreateQueryIndexManagerWithEncryptionKeyNilProvider
        * testCreateQueryIndexManagerWithEncryptionKeyNilProviderDoesNotCipherIndex
        * testCreateQueryIndexManagerWithEncryptionKeyNilProviderFailsIfDBExistsAndItIsEncrypted
    * Encryption only
        * testCreateQueryIndexManagerWithFixedKeyProvider
        * testCreateQueryIndexManagerWithFixedKeyProviderCiphersIndex
        * testCreateQueryIndexManagerWithFixedKeyProviderFailsIfDBExistsAndItIsNotEncrypted
        * testCreateQueryIndexManagerWithFixedKeyProviderFailsIfDBIsEncryptedButKeyIsWrong
        * testTextSearchIsAvailable

1. DatastoreEncryptionTests
    * Common
        * testEncryptionKeyProviderReturnsTheSameProviderUsedToCreateTheDatastore
        * testInitReturnsNilIfEncryptionKeyProviderReturnsAValueAndDBIsNotEncrypted
        * testInitReturnsNilIfEncryptionKeyProviderReturnsAValueWithAnAlreadyOpenNonEncryptedDB
        * testInitReturnsNilIfEncryptionKeyProviderReturnsNilAndDBIsEncrypted
        * testInitWithoutEncryptionKeyThrowsException
        * testInitWithoutEncryptionKeyThrowsExceptionAlthoughDBIsAlreadyOpen
    * Unencrypted only
        * testInitReturnsNilIfEncryptionKeyProviderReturnsAValueAndDBIsEncrypted
    * Encryption only
        * testInitReturnsNilIfEncryptionKeyProviderDoesNotReturnTheKeyUsedToCipherTheDatabase
        * testInitReturnsNilIfEncryptionKeyProviderDoesNotReturnTheKeyUsedToOpenTheDatabase
        * testInitReturnsNilIfEncryptionKeyProviderReturnsNilWithAnAlreadyOpenEncryptedDB

1. DatastoreManagerEncryptionTests
    * Common
        * testDatastoreNamedThrowsExceptionIfKeyProviderIsNil
        * testDatastoreNamedThrowsExceptionIfKeyProviderIsNilAlthoughDBWasOpenedBefore
        * testDatastoreNamedReturnsNilIfEncryptionKeyProviderReturnsNilAndDBIsEncrypted
        * testDatastoreNamedReturnsNilIfEncryptionKeyProviderReturnsAValueAndDBIsNotEncrypted
        * testDatastoreNamedReturnsNilIfEncryptionKeyProviderReturnsAValueWithAnAlreadyOpenNonEncryptedDB
    * Unencrypted only
        * testDatastoreNamedReturnsNilIfEncryptionKeyProviderReturnsAValueAndDBIsEncrypted
    * Encryption only
        * testDatastoreNamedReturnsNilIfEncryptionKeyProviderDoesNotReturnTheKeyUsedToCipherTheDatabase
        * testDatastoreNamedReturnsNilIfEncryptionKeyProviderDoesNotReturnTheKeyUsedToOpenTheDatabase
        * testDatastoreNamedReturnsNilIfEncryptionKeyProviderReturnsNilWithAnAlreadyOpenEncryptedDB

1. TD_DatabaseEncryptionTests
    * Common
        * testCreateEmptyWithEncryptionKeyNilProviderDoesNotCipherDatabase
        * testOpenFailsIfEncryptionKeyProviderReturnsAValueWithANonEncryptedDatabase
        * testOpenFailsIfEncryptionKeyProviderReturnsNilWithAnEncryptedDatabase
        * testReopenWithoutEncryptionKeyThrowsException
        * testReopenFailsIfEncryptionKeyProviderReturnsAValueWithANonEncryptedDatabase
        * testOpenWithoutEncryptionKeyThrowsException
    * Unencrypted only
        * testCreateEmptyWithFixedKeyProviderFails
        * testOpenFailsIfEncryptionKeyProviderReturnsAValue
        * testOpenFailsIfEncryptionKeyProviderReturnsAValueWithAnEncryptedDatabase
    * Encryption only
        * testCreateEmptyWithFixedKeyProviderCiphersDatabase
        * testOpenDoesNotFailIfEncryptionKeyProviderReturnsAValue
        * testOpenFailsIfEncryptionKeyProviderDoesNotReturnTheKeyUsedToCipherTheDatabase
        * testReopenFailsIfEncryptionKeyProviderDoesNotReturnTheKeyUsedToCipherTheDatabase
        * testReopenFailsIfEncryptionKeyProviderReturnsNilWithAnEncryptedDatabase

**Comment by rhyshort** [comment]
#345 merged bringing in fixes to the CDTDatastore build, compatibility with CocoaPods 1.1.1, and restored the encryption tests.
