### ISSUE TITLE
CDTPullReplication constructor parameter types are wrong

### ISSUE THREAD

**Issue by pwcremin** [cloudant/CDTDatastore#347]
e.g. In CDTPullReplication the 'target' is type CDTDatastore*, it should be NSURL*.  

@implementation CDTPullReplication
+ (instancetype)replicationWithSource:(NSURL *)source target:(CDTDatastore *)target

@implementation CDTPushReplication
+ (instancetype)replicationWithSource:(CDTDatastore *)source target:(NSURL *)target

**Comment by tomblench** [comment]
For pull replication the source is a remote database (`NSURL`) and the target is the local database (`CDTDatastore`).

For push replication the source is the local database (`CDTDatastore`) and the target is a remote database (`NSURL`).

See our documentation for more details, including the code samples in https://github.com/cloudant/CDTDatastore/blob/master/doc/replication.md
