### ISSUE TITLE
specification for `FMDB (= 2.6)`

### ISSUE THREAD

**Issue by yaseenox** [cloudant/CDTDatastore#348]
Hi, when I try to run (pod install) I get this message:
[!] Unable to find a specification for `FMDB (= 2.6)` depended upon by `CDTDatastore/standard`

**Comment by rhyshort** [comment]
That's strange are you using the latest version of CocoaPods? Is the master spec repo up to date on your machine?

**Comment by yaseenox** [comment]
will I updated CocoaPods and the master repo and the problem solved eventually. thank you very much, I appreciate your help.

**Comment by rhyshort** [comment]
No problem :)
