### ISSUE TITLE
CloudantSyncTests and CloudantTests

### ISSUE THREAD

**Issue by rhyshort** [cloudant/CDTDatastore#351]
CloudantSyncTests and CloudantTests classes contain methods that are useful to many tests, it should be considered to merge them, or more cleanly divide the functions between the classes. For example path generation could be pushed up if a merge is decided not to be the best course of action.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
