### ISSUE TITLE
[help] query structure for find.

### ISSUE THREAD

**Issue by yaseenox** [cloudant/CDTDatastore#352]
Hi, is the code a right query structure ? because when I tried it I got an error message.
"articles" is an array in "datastoreTopics" I want to get all the "topics" that have more than one article.

Code:
NSDictionary *query = @{@"articles" : @{@"$not" : @{@"$size":@1}} };
CDTQResultSet *result = [datastoreTopics find:query
									skip:_pageIndex
									limit:_pageSize
									fields:fields
									sort:sortDocument];
Error : 
DB Error: 1 "near "?": syntax error"
DB Query: SELECT _id FROM "_t_cloudant_sync_query_index_basic" WHERE _id NOT IN (SELECT _id FROM "_t_cloudant_sync_query_index_basic" WHERE "articles" (null) ?);

**Comment by rhyshort** [comment]
Hi,

Yes that is the correct Query structure, our [query grammar doc](https://github.com/cloudant/CDTDatastore/blob/master/doc/query.md#grammar)  provides the full grammar for query. 

I am pretty sure this is a bug and your query should be working correctly. What version of CDTDatastore are you using and on which platform?

**Comment by yaseenox** [comment]
I am using  'CDTDatastore', '1.1.1'
on (iOS 9.0) objective-C application.

**Comment by rhyshort** [comment]
I've reproduced with 1.2.0

**Comment by yaseenox** [comment]
is there any alternative way to do it ?

**Comment by rhyshort** [comment]
Unfortunately I don't think there is an easy way of doing the same thing.

**Comment by yaseenox** [comment]
I figure out the problem, I was using "articles" as "ensureIndexed" I dont know what is the reason but when I delete it from the "ensureIndexed" and delete the app from the device and reinstall it, the query "@{@"articles" : @{@"$not":@{@"$size":@1}}}" worked fine.

**Comment by rhyshort** [comment]
Glad you've found a work around, but I'm sure this a bug with our operator handling, so I reopening.
