### ISSUE TITLE
Using selector to filter replication

### ISSUE THREAD

**Issue by sventepe** [cloudant/CDTDatastore#361]
Hi,

I'm just getting started with CouchDB/Cloudant and I'm trying to replicate some of the ~800k docs in my DB to an iOS client. I started by using a "classic filter", this takes 27! minutes for the initial run in the browser (added heartbeat parameter to keep it running). The CDTReplicator stops with an error after 60s, looks like a timeout:
Error Domain=TDChangeTracker Code=589 "(null)"

I would like to switch to selectors for filtering, as recommended in the Cloudant docs, but I can't find a way to use a selector with the CDTReplicator.

Any help appreciated.

Regards

Sven

**Comment by sventepe** [comment]
Solved this myself by using a CDTHTTPInterceptor to intercept the outgoing request. On the CDTReplicator I set filter to "_selector" and then changed the intercepted request to POST and set the interceptor JSON as body.

**Comment by Fenil15** [comment]
@sventepe Thank you for providing a workaround for same issue faced by me.
