### ISSUE TITLE
Support `_selector` syntax in pull replications

### ISSUE THREAD

**Issue by tomblench** [cloudant/CDTDatastore#362]
See #361 

From [the documentation](http://docs.couchdb.org/en/2.0.0/api/database/changes.html#selector), this feature is new in version 2.0 and is "significantly more efficient than using a JavaScript filter function and is the recommended option if filtering on document attributes only"

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
