### ISSUE TITLE
Encryption : 'Couldn't Create database.'

### ISSUE THREAD

**Issue by JoellyR** [cloudant/CDTDatastore#363]
Hi,

I have been getting the following error for sometime, and i was trying to pin point a reproducable case... and i seem to have one now. The error is:

`user db: Error Domain=CDTDatastoreErrorDomain Code=400 "Couldn't create database." UserInfo={NSLocalizedRecoverySuggestion=Wrong key?, NSLocalizedDescription=Couldn't create database., NSLocalizedFailureReason=Wrong key?}`

This seems to reproducible on installing the app on iPads with the encryption turned on.. this can be fixed by changing the password... but then it seems like it doesn't work on the next device until you change the password again. 

On existing apps you can reproduce this by: Going into the code and changing the "forIdentifier" when initializing "CDTEncryptionKeychainProvider" (You will see what i mean in my code below)... then deleting the existing app then trying to reinstall the app.. The only way to get by this seems to be changing back to the old identifier or (weirdly enough) by changing the password value for "CDTEncryptionKeychainProvider".... 

This is a struggle as when it doesn't work on new devices deploying a new version just to change the password doesnt make sense.

code:
 ```
let fileManager = FileManager.default
            
            let documentsDir = fileManager.urls(for: .documentDirectory, in: .userDomainMask).last!
            
            let testStoreURL = documentsDir.appendingPathComponent("test-datastore")
            let path = userStoreURL.path
            
            
            //*****this is the values of identifier and password i was referring to before*****
            let encryptionProvider = CDTEncryptionKeychainProvider.init(password: "passw1rd", forIdentifier: "testtest")
            
            let manager = try CDTDatastoreManager(directory: path)
            testDatastore =  try manager.datastoreNamed("testdb", with: encryptionProvider)

```

**Comment by tomblench** [comment]
@JoellyR looking at your sample code it appears that you are trying to use a different identifier with the same password, which won't work. You can have multiple identifier/password pairs, which are analogous to username/password pairs.

If you don't care about the identifier (you only have one datastore on the device, or you are happy to use the same password for all of them), then you can use a constant string like `"default"` (as per https://github.com/cloudant/CDTDatastore/blob/master/doc/encryption.md).

Additionally we don't currently support changing the password - see https://github.com/cloudant/CDTDatastore/issues/279

**Comment by JoellyR** [comment]
@tomblench Thanks for your reply :) I have some understanding of what you are saying, though... the biggest issue seems to be this happens when installing on to a completely new device and thats what seems to be a bit confusing. Any thoughts on that? - thanks in advance

**Comment by tomblench** [comment]
@JoellyR OK that's interesting, sorry if I mis-understood your original report. Do you mean the following steps?

- Create encrypted database with CDTDatastore on device 1
- Copy encrypted database from device 1 to device 2
- Try and open encrypted database with CDTDatastore on device 2

If so, I don't think we've tested this scenario and I'll try to reproduce the issue, because I suspect there is a bug preventing this from working correctly.

**Comment by JoellyR** [comment]
@tomblench  Hey sorry if I was not to clear in my initial report. If i try to put it as basically as possible... I use the above code to enable encryption.. it seems to work 100% on my device... then for whatever reason i install the application on a new device (exact same code) and all of a sudden the i start getting the  error: 

`user db: Error Domain=CDTDatastoreErrorDomain Code=400 "Couldn't create database." UserInfo={NSLocalizedRecoverySuggestion=Wrong key?, NSLocalizedDescription=Couldn't create database., NSLocalizedFailureReason=Wrong key?}`

**** SIDE NOTE: Though i did find that if i take the ipad it is failing on and reinstall a new version with the password (in code) changed then it seems to work.

**Comment by tomblench** [comment]
@JoellyR can you please reproduce with logging switched on?

You'll need this import:
```objective-c
#import "CDTLogging.h"
```
and these lines
```
    [DDLog addLogger:[DDTTYLogger sharedInstance]];
    [DDLog addLogger:[DDASLLogger sharedInstance]];
    
    CDTChangeLogLevel(CDTINDEX_LOG_CONTEXT, DDLogLevelDebug);
    CDTChangeLogLevel(CDTREPLICATION_LOG_CONTEXT, DDLogLevelDebug);
    CDTChangeLogLevel(CDTDATASTORE_LOG_CONTEXT, DDLogLevelDebug);
    CDTChangeLogLevel(CDTDOCUMENT_REVISION_LOG_CONTEXT, DDLogLevelDebug);
    CDTChangeLogLevel(CDTTD_REMOTE_REQUEST_CONTEXT, DDLogLevelDebug);
    CDTChangeLogLevel(CDTTD_JSON_CONTEXT, DDLogLevelDebug);
```
this code should execute first, that is, before opening the datastore.

It seems like this is an issue with the KeyChain but the log output should help us narrow it down.

**Comment by JoellyR** [comment]
@tomblench i am using swift not obj-c.. so when i try to import CDTLogging I cant seem to find a module with that name... i tried putting it my bridging-header and that didn't seem to work either... I can find the  DDLog class but the CDTChangeLogLevel doesn't seem to be anywhere. Sorry but are there any extra steps i would need to import CDTLogging in swift?

**Comment by tomblench** [comment]
@JoellyR unfortunately the bridging header won't bring in CDTChangeLogLevel because it's declared as a macro. If possible you could write a small objective-c file containing a method to change the log level and call that from your swift code.

**Comment by JoellyR** [comment]
@tomblench  Below is the stack from with the add logger code:

```
2017-05-10 13:23:34:338 DC[8594:5163898] Open /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb (flags=200006)
2017-05-10 13:23:34.344115 DC[8594:5163947] Open /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb (flags=200006)
2017-05-10 13:23:34.409736 DC[8594:5163948] This option is not available in standard SQLite, use SQLCipher instead
2017-05-10 13:23:34:408 DC[8594:5163898] This option is not available in standard SQLite, use SQLCipher instead
2017-05-10 13:23:34.411230 DC[8594:5163948] Key to decrypt DB at /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb not set. DB can not be opened.
2017-05-10 13:23:34:410 DC[8594:5163898] Key to decrypt DB at /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb not set. DB can not be opened.
2017-05-10 13:23:34:412 DC[8594:5163898] Key not set for DB at /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb: Error Domain=FMDatabaseEncryptionKeyErrorDomain Code=0 "Key to decrypt DB not set" UserInfo={NSLocalizedDescription=Key to decrypt DB not set}
2017-05-10 13:23:34.413277 DC[8594:5163948] Key not set for DB at /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb: Error Domain=FMDatabaseEncryptionKeyErrorDomain Code=0 "Key to decrypt DB not set" UserInfo={NSLocalizedDescription=Key to decrypt DB not set}
2017-05-10 13:23:34.416572 DC[8594:5163947] DEALLOC <TD_DatabaseManager: 0x170037520>
2017-05-10 13:23:34:415 DC[8594:5163898] DEALLOC <TD_DatabaseManager: 0x170037520>
2017-05-10 13:23:34.417323 DC[8594:5163948] CLOSING <TD_DatabaseManager: 0x170037520> ...
2017-05-10 13:23:34:416 DC[8594:5163898] CLOSING <TD_DatabaseManager: 0x170037520> ...
2017-05-10 13:23:34.418054 DC[8594:5163948] CLOSED <TD_DatabaseManager: 0x170037520>
2017-05-10 13:23:34:417 DC[8594:5163898] CLOSED <TD_DatabaseManager: 0x170037520>
Encountered an error in initializing the user db: Error Domain=CDTDatastoreErrorDomain Code=400 "Couldn't create database." UserInfo={NSLocalizedRecoverySuggestion=Wrong key?, NSLocalizedDescription=Couldn't create database., NSLocalizedFailureReason=Wrong key?}
```

**Comment by JoellyR** [comment]
@tomblench  this is the stack trace of a device that works with encryption... but once i delete the app and change the identifier (in code):

```
2017-05-10 13:23:34:338 DC[8594:5163898] Open /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb (flags=200006)
2017-05-10 13:23:34.344115 DC[8594:5163947] Open /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb (flags=200006)
2017-05-10 13:23:34.409736 DC[8594:5163948] This option is not available in standard SQLite, use SQLCipher instead
2017-05-10 13:23:34:408 DC[8594:5163898] This option is not available in standard SQLite, use SQLCipher instead
2017-05-10 13:23:34.411230 DC[8594:5163948] Key to decrypt DB at /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb not set. DB can not be opened.
2017-05-10 13:23:34:410 DC[8594:5163898] Key to decrypt DB at /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb not set. DB can not be opened.
2017-05-10 13:23:34:412 DC[8594:5163898] Key not set for DB at /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb: Error Domain=FMDatabaseEncryptionKeyErrorDomain Code=0 "Key to decrypt DB not set" UserInfo={NSLocalizedDescription=Key to decrypt DB not set}
2017-05-10 13:23:34.413277 DC[8594:5163948] Key not set for DB at /var/mobile/Containers/Data/Application/D775FD6B-31DD-49A4-8905-C715AE0F5D85/Documents/user-datastore/userdb.touchdb: Error Domain=FMDatabaseEncryptionKeyErrorDomain Code=0 "Key to decrypt DB not set" UserInfo={NSLocalizedDescription=Key to decrypt DB not set}
2017-05-10 13:23:34.416572 DC[8594:5163947] DEALLOC <TD_DatabaseManager: 0x170037520>
2017-05-10 13:23:34:415 DC[8594:5163898] DEALLOC <TD_DatabaseManager: 0x170037520>
2017-05-10 13:23:34.417323 DC[8594:5163948] CLOSING <TD_DatabaseManager: 0x170037520> ...
2017-05-10 13:23:34:416 DC[8594:5163898] CLOSING <TD_DatabaseManager: 0x170037520> ...
2017-05-10 13:23:34.418054 DC[8594:5163948] CLOSED <TD_DatabaseManager: 0x170037520>
2017-05-10 13:23:34:417 DC[8594:5163898] CLOSED <TD_DatabaseManager: 0x170037520>
Encountered an error in initializing the user db: Error Domain=CDTDatastoreErrorDomain Code=400 "Couldn't create database." UserInfo={NSLocalizedRecoverySuggestion=Wrong key?, NSLocalizedDescription=Couldn't create database., NSLocalizedFailureReason=Wrong key?}
```

**Comment by tomblench** [comment]
Changing the identifier or installing on a new device means that the keychain entry won't be present. You can only open an encrypted database if the keychain entry generated at database creation time is present.

The steps involved with creating a new encrypted database are:
- Generate a string of random bytes to use as the encryption key
- Store this encryption key, protected by the given password, on the keychain
- Use the encryption key to create the encrypted database with SQLCipher

The steps involved with opening an existing encrypted database are:
- Look up encryption key in keychain protected by the given password
- If the keychain entry exists, and the encryption key is correct, open the encrypted database

Most of this work happens [here](https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/Encryption/Keychain/CDTEncryptionKeychainStorage.m) in our code. You can see we use the `SecItem{Add,CopyMatching}` APIs to create and read entries in the keychain. (See also https://developer.apple.com/reference/security/keychain_services)

As you can see, if the device is reset (removing keychain contents), or an app with an existing database is moved to a new device, then there is no longer a keychain entry which is needed to decrypt the database. I'm not 100% sure but I suspect that removing an app will also remove its associated keychain entries. 

If using the keychain is not suitable for your app, you could also use `CDTEncryptionKeySimpleProvider` but this may pose security issues especially if you hard-code the password in your app (which we _do not_ recommend doing!)

**Comment by JoellyR** [comment]
@tomblench  

> or an app with an existing database is moved to a new device

First thank you for really keeping in touch and replying so often! Though i am still a bit confused because we are not moving the database to the new device... it seems to happen on a fresh install... let say just installing the app from our MDM on to a new device.

**Comment by JoellyR** [comment]
@tomblench just to let you know we are using the cloudant-sync just as a local document storage. There is no connection to a remote cloudant database or syncing or anything going on

**Comment by JoellyR** [comment]
@tomblench any updates?

**Comment by vladmoh** [comment]
The issue is in the following method of  TD_Database.m:

result comes back as nil on new devices. Database is not moved from other devices. The data file is being created brand new and Cloudant Sync is failing to initialize the file.
(lldb) po _path
/var/mobile/Containers/Data/Application/4C233FFC-61D2-44E7-9B5F-AF8EB6BF28EB/Documents/datastore22/mydb2.touchdb

Could it have something to do with keychain?

`// callers: -open, -compact
- (BOOL)openFMDBWithEncryptionKeyProvider:(id<CDTEncryptionKeyProvider>)provider
{
    __block BOOL result = YES;

    // Create database
    FMDatabaseQueue* queue = nil;
    
    if (result) {
        queue = [TD_Database queueForDatabaseAtPath:_path readOnly:_readOnly];
        
        result = (queue != nil);
    }

    // Set key to cipher database (if available)
    if (result) {
        [queue inDatabase:^(FMDatabase* db) {
          NSError* error = nil;
          result = [db setKeyWithProvider:provider error:&error];
          **if (!result) {
              CDTLogError(CDTDATASTORE_LOG_CONTEXT, @"Key not set for DB at %@: %@", _path, error);
          }**
        }];
    }
`

**Comment by vladmoh** [comment]
(lldb) po error
Error Domain=FMDatabaseEncryptionKeyErrorDomain Code=0 "Key to decrypt DB not set" UserInfo={NSLocalizedDescription=Key to decrypt DB not set}

**Comment by vladmoh** [comment]
The issue is in our version of FMDatabase+EncryptionKey.m

ENCRYPT_DATABASE macro is not setup anywhere and by default falls down to the else statement.

If removed - everything seems to work fine.

```
#pragma mark - Private methods
- (BOOL)setEncryptionKey:(CDTEncryptionKey *)encryptionKey
{
#ifdef ENCRYPT_DATABASE
    NSString *hexEncryptionKey = TDHexFromBytes(encryptionKey.data.bytes, CDTENCRYPTIONKEY_KEYSIZE);
    NSString *pragmaSetKey =
        [NSString stringWithFormat:@"PRAGMA key = \"x'%@'\";", hexEncryptionKey];

    return [self executeUpdate:pragmaSetKey];
#else
    CDTLogError(CDTDATASTORE_LOG_CONTEXT,
                @"This option is not available in standard SQLite, use SQLCipher instead");

    return NO;
#endif
}

```

**Comment by rhyshort** [comment]
I think this would mean the root of the problem is with CocoaPods since the podspec for encryption adds the required files 
```ruby
sp.xcconfig = { 'OTHER_CFLAGS' => '$(inherited) -DENCRYPT_DATABASE' }
```

Source: https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore.podspec#L53

So this does bring so obvious questions such as does it work with older versions of cocapods and are you specifying the encrypted version of the pod.

**Comment by vladmoh** [comment]
To fix the issue in Xcode, go to PROJECT settings -> Build Settings
Search for Preprocessor Macros by typing "prepro" in the upper right search entry field.
Modify Debug, Release and whatever other targets that you may have to add ENCRYPT_DATABASE=1

This change should result in the following added to your project.pbxproj file:

				GCC_PREPROCESSOR_DEFINITIONS = (
					"DEBUG=1",
					"$(inherited)",
					**"ENCRYPT_DATABASE=1",**
				);

**Comment by vladmoh** [comment]
and for each target it also adds

				GCC_PREPROCESSOR_DEFINITIONS = "ENCRYPT_DATABASE=1";

in project.pbxproj

**Comment by vladmoh** [comment]
Hello,

still a problem when running builds through Jenkins.

Seems like ObjectiveC compiler doesn't get run with the macro. I found the following lines in the build log:

CompileC /Users/dcbuildadmin/Library/Developer/Xcode/DerivedData/DC-ecizuvfhijsvmkavqcdnnafsvblo/Build/Intermediates/Pods.build/Distribution-iphoneos/CDTDatastore.build/Objects-normal/armv7/FMDatabase+EncryptionKey.o CDTDatastore/CDTDatastore/Encryption/FMDatabase+EncryptionKey.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=....... 
 /Build/Products/Distribution-iphoneos/SQLCipher -**DENCRYPT_DATABASE** -include /Users/..../CDTDatastore-prefix.pch -MMD -MT dependencies -MF  ..... -A4EEOQH4EICCRFEJFL3HQG4MQRA7ERUWBDJQL4NNQWK2JJIYOH2Q/Pods/CDTDatastore/CDTDatastore/Encryption/FMDatabase+EncryptionKey.m -o /Users/...../Build/Intermediates/Pods.build/Distribution-iphoneos/CDTDatastore.build/Objects-normal/arm64/FMDatabase+EncryptionKey.o


Seems like the macro is added for clang, but not for CompileC.
Does it need to be there?
Can the code be changed to rely on parameter rather than macro?
For example specific encryption providers or something like that?
