### ISSUE TITLE
CDTChangeLogLevel can't be called from swift

### ISSUE THREAD

**Issue by tomblench** [cloudant/CDTDatastore#365]
Even if CDTLogging is added to the bridging header, `CDTChangeLogLevel` is not available because it was declared as a macro.

See also #363

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
