### ISSUE TITLE
Server-side delete leads to document resurrection on replication

### ISSUE THREAD

**Issue by sventepe** [cloudant/CDTDatastore#366]
Hi,

I delete a document on the server, which has been modified on the client. When the client replicates, conflict handling is not triggered, as this seems to handle only leafs that are not deleted. I need the document to stay deleted, how can I achieve that? The CouchDB docs state _deleted_conflicts would be a place to get the deleted document. Can I query the deleted documents and prevent my local change from beeing replicated?
This post further describes the problem:
http://stackoverflow.com/questions/13043927/resolving-replication-conflicts-for-deleted-documents-in-couchdb

Regards

Sven

**Comment by tomblench** [comment]
This behaviour mimics CouchDB. You can try the same thing between two Cloudant or CouchDB databases.

In the sample below shows a `curl` query after doing something similar to your example: I
- Created a document on `atestdb1`
- Replicated it to `atestdb2`
- Edited it on `atestdb1`
- Deleted it on `atestdb2`
- Replicated from `atestdb2` to `atestdb1`

```
17:26:09 in ~$ curl http://tomblench.cloudant.com/atestdb1/foo?meta=true
{"_id":"foo","_rev":"2-1bbf46f6252a4b4a59888c9e5dc48434","goodbye":"world","_revs_info":[{"rev":"2-1bbf46f6252a4b4a59888c9e5dc48434","status":"available"},{"rev":"1-15f65339921e497348be384867bb940f","status":"available"}],"_deleted_conflicts":["2-2d715caed35974bb33de24d1d6c95779"]}
```

You can see that by asking for `meta=true` (or `deleted_conflicts=true`) you can see the deleted revision, but if you just ask for `conflicts=true` it won't show up:

```
17:29:14 in ~$ curl http://tomblench.cloudant.com/atestdb1/foo?conflicts=true
{"_id":"foo","_rev":"2-1bbf46f6252a4b4a59888c9e5dc48434","goodbye":"world"}
```

If it's important to emulate `deleted_conflicts=true` we could consider this as a feature request for the conflict resolver.

**Comment by sventepe** [comment]
Thank you, that was the hint I needed! Now I modified activeRevisionsForDocumentId:database: and getConflictedDocumentIdsWithDatabase: to include deleted revisions. Now I can process them in my ConflictResolver and pick the delete as winning revision.

I was just going deep with the TDPuller when I read your answer, you saved me from a lot of pain ;)

Having that configurable with the conflict resolver would be fantastic!

**Comment by tomblench** [comment]
OK, It's good that you can work around this issue for the time being. I have raised #367 which would emulate `deleted_conflicts=true`.
