### ISSUE TITLE
Support `deleted_conflicts` mode in conflict resolver

### ISSUE THREAD

**Issue by tomblench** [cloudant/CDTDatastore#367]
See #366.

This feature may be useful for some users who don't want remote deleted documents to be superseded by newer local documents. Couch supports this through the `deleted_conflicts` flag and we should offer a similar API.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
