### ISSUE TITLE
Duplicate `GTMDefines.h`

### ISSUE THREAD

**Issue by seanhealy** [cloudant/CDTDatastore#369]
It seems that CDTDatastore includes a [few select files from GoogleToolboxForMac](https://github.com/cloudant/CDTDatastore/tree/master/CDTDatastore/vendor/google-toolbox-for-mac). I already have GoogleToolboxForMac included in my workspace as it's a dependency for Firebase Messaging.

After adding CDTDatastore GoogleToolboxForMac is unable to find its `GTMDefines.h` file. (I'm assuming this is because CDTDatastore is first in the search path. I'm not sure if this is a known issue or if there is an easy way I can configure things to limit the search path of each to their relevant files.

We're just working on a prototype right now that will use CDTDatastore. If we end up going this direction I'll look into it further but, I just didn't see an issue around this so I thought I'd check in early incase the answer is simple.

Thanks!

**Comment by tomblench** [comment]
@seanhealy we have a fix for this and we hope to publish a new release of the library within the next few days. We'll notify you when it's ready.
