### ISSUE TITLE
Threading issues in [TDPuller stop]

### ISSUE THREAD

**Issue by tomblench** [cloudant/CDTDatastore#384]
See also #383 

Starting multiple replicators and then stopping some or all of them at various stages of progress is sufficient to cause various exceptions or to get the replicator stuck in the "stopping" state.

It would appear that we need some better synchronisation primitives to protect the state shared between the methods in this class.

**Comment by joergbirkhold** [comment]
is there any progress on that issue, my client is getting a bit nervous...

**Comment by tomblench** [comment]
@joergbirkhold unfortunately these is still other work prioritised above this. If you are a Cloudant customer then we can escalate the priority - you can do this by contacting Cloudant support and referencing this ticket.

**Comment by joergbirkhold** [comment]
aye sure we are and i think quite a big one. i will check with the support

**Comment by joergbirkhold** [comment]
Is there a branch which i could use for testing? 
I was in contact with the support.... did it help?

**Comment by tomblench** [comment]
@joergbirkhold we merged PR #389 to master which fixed some threading issues, but this also included some more rigorous tests which exposed some more issues after the merge.

We currently have #394 open to address these extra issues.

So you can try latest master which might address your issues or look at #394 (the branch is `dispatch-sync-bulk-get-probe`), but this is liable to change as it hasn't yet been fully reviewed.

Contacting support allowed us to validate that you are a Cloudant customer and prioritise appropriately so, in short, it did help :)

**Comment by tomblench** [comment]
Closing, this has merged to master now.
