### ISSUE TITLE
REST API support?

### ISSUE THREAD

**Issue by dyowee** [cloudant/CDTDatastore#386]
Good day,

I am hoping to upgrade from Couchbase lite to CDTDatastore, since we are using CouchDB on the backend, and CDTDatastore seems to support CouchDB better (hopefully CouchDB 2.0). But does it support/intercept like in the old TouchDB?

Thanks.

**Comment by emlaver** [comment]
Hello @dyowee, the original data structures of CDTDatastore were forked from TouchDB.  Have you had a chance to look at the [CRUD API document](https://github.com/cloudant/CDTDatastore/blob/master/doc/crud.md)?

**Comment by ricellis** [comment]
@dyowee I'm not sure about what function "support/intercept" is referring to, but based on the title of the ticket if you are also asking if CDTDatastore provides or exposes a HTTP/REST endpoint for the iOS on-device database, then the answer is no.
