### ISSUE TITLE
How to use Basic Authentication?

### ISSUE THREAD

**Issue by azri92** [cloudant/CDTDatastore#393]
In the [Changelog](https://github.com/cloudant/CDTDatastore/blob/master/CHANGELOG.md#110-2016-06-17), I can see that:

> Replications will use session cookies to authenticate rather than using Basic Auth for every request.

So, how do we use Basic Authentication instead? This is possible in [sync-android](https://github.com/cloudant/sync-android#authentication). But I can't find any mention of this in CDTDatastore's docs.

**Comment by ricellis** [comment]
You'll need to implement a `CDTHTTPInterceptor` `-interceptRequestInContext` that adds the `Authorization` header to the `request` and add that interceptor to your replication.
See https://github.com/cloudant/CDTDatastore/blob/master/doc/httpinterceptors.md for more information about interceptors.

Out of curiosity what is the use-case that means the session cookie doesn't work for you?

**Comment by azri92** [comment]
Thanks for the reply.

The CouchDB server I'm connecting to doesn't have cookie auth up yet, so I just had to fallback to basic auth.
