### ISSUE TITLE
Investigate timing-related failures in testRemoteLastSequenceValueAfter{Pull,Push}Replication

### ISSUE THREAD

**Issue by tomblench** [cloudant/CDTDatastore#395]
There appears to be a failure reading back a checkpointed sequence number in these tests, which is timing-related. There should be a guarantee that if the read of the sequence number happens after the write, it will be the correct value, because all of the work is done on the same queue. But this does not always appear to be the case (this is an intermittent bug and happens on some Jenkins test runs).

The short term fix has been to introduce a small delay in the test after finishing replication.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
