### ISSUE TITLE
Getting couple of Xcode warnings with Xcode version 9.1

### ISSUE THREAD

**Issue by navaneet** [cloudant/CDTDatastore#407]
Hi, 

We are using the latest version of CDTDatastore 1.2.2 however are getting a few warnings related to CDTDatastore while building the app.

We are using Swift 4 and have use_frameworks! in place. I have attached the screenshots below:

<img width="969" alt="screen shot 2017-11-22 at 5 08 43 pm" src="https://user-images.githubusercontent.com/2356187/33125889-669ee7de-cfa8-11e7-89d3-a6fd37812dbe.png">

<img width="343" alt="screen shot 2017-11-22 at 5 13 32 pm" src="https://user-images.githubusercontent.com/2356187/33125926-8aeb6036-cfa8-11e7-812e-f0918c8cac86.png">
<img width="342" alt="screen shot 2017-11-22 at 5 13 48 pm" src="https://user-images.githubusercontent.com/2356187/33125927-8b36c8c8-cfa8-11e7-9d24-e1e5165d2c20.png">

**Comment by tomblench** [comment]
@navaneet tried to reproduce in XCode 9.1 and didn't get a warning - shown below are the signatures for all of the delegate methods

```swift
class MyDel : NSObject, CDTReplicatorDelegate
{
    func replicatorDidComplete(_ replicator: CDTReplicator) {
    }
    
    func replicatorDidError(_ replicator: CDTReplicator?, info: Error) {
    }
    
    func replicatorDidChangeState(_ replicator: CDTReplicator) {
    }
    
    func replicatorDidChangeProgress(_ replicator: CDTReplicator) {
    }
}
```

**Comment by navaneet** [comment]
K let me try something, will provide you with more details tomorrow as to why it might be showing up. I did see somewhere that there might be an xcode bug related to the above mentioned warning.

**Comment by navaneet** [comment]
@tomblench I guess the issue is similar to what I saw in stackoverflow https://stackoverflow.com/questions/39495773/xcode-8-warning-instance-method-nearly-matches-optional-requirement

**Comment by tomblench** [comment]
OK, closing
