### ISSUE TITLE
how to delete multiple docuements in cloudant db ios ???

### ISSUE THREAD

**Issue by Akshaysavaliya16** [cloudant/CDTDatastore#412]
Hello All,
I have to use IBM Cloudant NoSQL DB in my ios app.

I want to delete multiple documents from cloudant using ios CDTDatastore SDK.....

i've already use this below function using one by one delete.

```
for deviceID in docIDS {

        try! datastore?.deleteDocument(withId: deviceID)
      }
```

but i want delete all documents IDS using one query....

Can you please tell me is there is any function or feature available in this SDK

Thanks
Akshay

**Comment by ricellis** [comment]
No, there is no function for deleting multiple documents at once from the on-device datastore. As you have shown it is possible to delete them in a loop.

**Comment by Akshaysavaliya16** [comment]
Thanks for the response......

but in my case i've 5k to 10k docuemntes for deletion..if i want to delete 5 to 10k documents in loop then it will take long time...so can you please tell me is there is any hack or something like that...

**Comment by tomblench** [comment]
@Akshaysavaliya16 you can perform SQL operations directly on the SQLite database but this is not supported, the schema is liable to change, and you do this at your own risk.

Alternatively, you could create a new on-device datastore and replicate the documents you want to keep from the server, then delete the old on-device datastore.
