### ISSUE TITLE
Error copying matching creds

### ISSUE THREAD

**Issue by pwcremin** [cloudant/CDTDatastore#415]
CDTDatastore v2.0

Everything works, but this error is sent to the output when doing replication

> CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
>     class = inet;
>     "m_Limit" = "m_LimitAll";
>     ptcl = htps;
>     "r_Attributes" = 1;
>     srvr = "7fa697e3-6b9e-4b1c-8419-7abd24c2a886-bluemix.cloudant.com";
>     sync = syna;
> }

Create replicationManager and push.  This causes the above output

```
    replicatorFactory = [[CDTReplicatorFactory alloc] initWithDatastoreManager:manager];
    
    remoteDatabaseURL = [NSURL URLWithString:databaseUrl];
    
    replicationManager = [[ReplicationManager alloc] initWithData:remoteDatabaseURL datastore:datastore replicatorFactory:replicatorFactory];

[replicationManager push: callback];
```

**Comment by smithsz** [comment]
Morning, we've occasionally seen this output in our logs too. It can be safely ignored. See [this](https://stackoverflow.com/a/46806008) SO answer for more details.
