### ISSUE TITLE
Is there any API fro Datastore deletion after x number of days

### ISSUE THREAD

**Issue by navaneet** [cloudant/CDTDatastore#423]
Hi,

We have a datastore that we create on the app side, where we store all the user created data in. 
This datastore is then synced on frequent intervals back to cloudant. Since the datastores are created multiple times based on the flight path origin and destination we usually end up with with a lot of these datastores. 

Is there any way to delete these datastores once the datastore have been successfully replicated back to cloudant and x number of days have passed?

Deleting the datastores immediately is not possible for us after a successful replication so we need to wait for x amount of days before proceeding with the deletion.

**Comment by emlaver** [comment]
Hi @navaneet, we do not have API for this application specific behavior.  
To delete a datastore, use [`CDTDatastoreManager's deleteDatastoreNamed`](https://github.com/cloudant/CDTDatastore/blob/33c27b00e577a97420f53807d77218a8f6cc6f04/CDTDatastore/CDTDatastoreManager.h#L53-L62) method.  
Examples for working with `CDTDatastore` objects: https://github.com/cloudant/CDTDatastore/blob/33c27b00e577a97420f53807d77218a8f6cc6f04/doc/crud.md#datastore-and-datastoremanager-objects

**Comment by navaneet** [comment]
OK Cool, what happens if we don't delete the datastores? Do they keep on growing with both the number of documents being inserted and number of datastores themselves increasing? They can't grow indefinitely right? So what strategy does the library provide for handling that scenario?

**Comment by emlaver** [comment]
@navaneet you can use the [replication delegate](https://github.com/cloudant/CDTDatastore/blob/master/doc/replication.md#using-a-replication-delegate) to handle what happens when the replicator changes state, completes, stops, etc.

You may also want to review our [replication policies documentation.](https://github.com/cloudant/CDTDatastore/blob/master/doc/replication-policies.md#replication-policies)

**Comment by ricellis** [comment]
You can compact old revisions in datastores to reduce their footprint: https://github.com/cloudant/CDTDatastore/blob/2.0.1/CDTDatastore/CDTDatastore.h#L242

**Comment by navaneet** [comment]
Ok thanks
