### ISSUE TITLE
xcode 10 beta showing errors during compilation

### ISSUE THREAD

**Issue by navaneet** [cloudant/CDTDatastore#441]
We were trying out the new xcode 10 beta before the upcoming iOS 12 release, however we have run into compiler issues with the CDTDatastore cocoapod.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
a) Download xcode 10 beta
b) Integrate CDTDatastore pod into a sample project
c) Run the project

### 2. What you expected to happen
Not to give compile errors

### 3. What actually happened
It gave compile errors

## Environment details
- Xcode Version
    >  10 beta
- iOS version
    > 11

<img width="350" alt="screen shot 2018-09-07 at 8 50 20 pm" src="https://user-images.githubusercontent.com/2356187/45228547-1684fc80-b2e1-11e8-8021-0468fc35c256.png">

**Comment by smithsz** [comment]
These might just be deprecated symbols. Have you tried configuring the project to use the legacy build system (in `File` > `Project/Workspace Settings`)?

**Comment by navaneet** [comment]
@smithsz  Yes already tried, same errors
