### ISSUE TITLE
Review disabled test testMultiThreadedReplication

### ISSUE THREAD

**Issue by tomblench** [cloudant/CDTDatastore#444]
See https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastoreReplicationAcceptanceTests/ReplicationAcceptance.m#L1732

This test has been disabled as it is blocking releases due to transient failures.

Re-visit this test and re-work assertions so they are not susceptible to transient/timing failures.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
