### ISSUE TITLE
Pod not up to date

### ISSUE THREAD

**Issue by MMOK82** [cloudant/CDTDatastore#445]
## Pod install does not install the lates code, e.g. TDBlobStore.h includes deprecated naming for common digest : SHA_DIGEST_LENGTH

This causes build issues in Xcode 10 and  iOS 12.

**Comment by tomblench** [comment]
@MMOK82 https://github.com/cloudant/CDTDatastore/pull/442 should have fixed this. Please try 2.1.1 which was just released today.

**Comment by MMOK82** [comment]
@tomblench I can only get 2.1.0 using cocopds:

I tried specifying the version 2.1.1 but got the following error:
[!] CocoaPods could not find compatible versions for pod "CDTDatastore":
  In Podfile:
    CDTDatastore (= 2.1.1)

I do see that the master branch when downloaded directly has the updated code version, but it would be very beneficial to be able to get as a pod to simple future updates.

Thank for the quick response "thumbs up!"

**Comment by ricellis** [comment]
Closing as the 2.1.1 pod was definitely published to cocoapods and is showing up as the [latest version](https://cocoapods.org/pods/CDTDatastore). Please re-open if you are still having issues.

**Comment by MMOK82** [comment]
@ricellis thanks for the update, I reviewed the setup and figured out that I was doing "pod install" which does not update the pod only "pod update" will. I had removed the pod and installed it again but a conflict had apparently caused an error. Once I changed this it was installed successfully. Thanks again for looking into this and sorry about the error on my side.
