### ISSUE TITLE
how can i get the progress value when downloading the database from remote server?

### ISSUE THREAD

**Issue by Akshaysavaliya16** [cloudant/CDTDatastore#446]
i have implement this library in my iOS app with the SDK....its working well..
my database size is almost 60 MB on remote server..i have downloading the database using CDTDatastor
`let datastoreWt = AppDelegate.appDelegateObject().datastoreWaterMeter
                datastoreWt?.pull(from: NSURL(string: waterMeterDB)! as URL, completionHandler: { (error) in 
}`
i just wanted to display the progress bar for users..how much data is downloaded from the remote server..is there anything that i can get the downloading progress and display into the progress bar.

can you please help me for this

Thanks 
Akshay

**Comment by smithsz** [comment]
Hi @Akshaysavaliya16, unfortunately there isn't a way to track the progress of downloads/replications at the moment. You can define a delegate that gets called every so often to confirm the replication is still ongoing (see the related issue #375). Apologies.
