### ISSUE TITLE
How to query for case insensitive text

### ISSUE THREAD

**Issue by navaneet** [cloudant/CDTDatastore#449]
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
```
        let query: JSONDict = ["user_name": "john"]
        var results: CDTQResultSet?
        results = self.dataStore?.find(query)
```

Say we are querying with the user_name john, is there a way in the query api to do case insensitive search so that that if the entered text is "john" and the text saved in db is "John" it returns the same instead of returning nil.

### 2. What you expected to happen

To return the user with the name "John"

### 3. What actually happened

Returns nil if case doesn't match

## Environment details
- Version(s) that are affected by this issue.
    > 2.1.1
- iOS/macOS version
    > iOS 12.1

**Comment by tomblench** [comment]
Text search is covered [indexing](https://github.com/cloudant/CDTDatastore/blob/master/doc/query.md#indexing-for-text-search) and [query](https://github.com/cloudant/CDTDatastore/blob/master/doc/query.md#text-search) are covered in the docs.

In the following example all searches would match "John Smith" (the default tokenizer will split on whitespace and perform case-folding - see the docs for more info on tokenizers).

```swift

datastore?.ensureIndexed(["user_name"], withName: "user_name", of:CDTQIndexType.text)
            
datastore?.find(["$text": ["$search":"JOHN"]])?.enumerateObjects { (doc, idx, stop) -> Void in
    print(doc.body)
}

datastore?.find(["$text": ["$search":"smith"]])?.enumerateObjects { (doc, idx, stop) -> Void in
    print(doc.body)
}

datastore?.find(["$text": ["$search":"jOhN sMiTh"]])?.enumerateObjects { (doc, idx, stop) -> Void in
    print(doc.body)
}
```

**Comment by navaneet** [comment]
OK thanks, so basically we have to create a text search index right? By the way does the index name need to be unique? We kind of use the db name for the index name and we already have one already for that particular db, do we need to create a separate index or append to the same index?

**Comment by navaneet** [comment]
@tomblench can we queries like this with text based search wherein we also mention the doc_type for example? We might not want the text search to search all throughout the database since we already know which document type to fetch it from, will the following query work?

datastore?.find(["$text": ["$search": "John"], "doc_type": name])?.enumerateObjects { (doc, idx, stop) -> Void in
    print(doc.body)
}

Also, if multiple texts are present, say both John and john, which one will the api return?

**Comment by tomblench** [comment]
Index names need to be unique and all matches will be returned. I imagine the above will work but you'll have to try it.

If you don't actually need full text search and tokenisation, another approach you could use is to do the case normalisation yourself, just uppercase the field on storage and then also uppercase the query string the user has entered.

**Comment by navaneet** [comment]
@tomblench  Thanks for the quick reply, we have a couple of old documents wherein the usernames are both in lowercase and first character upper cased, and these currently we can't modify hence asked if the query will return the first match only or all the possible matches.

**Comment by navaneet** [comment]
@tomblench I am closing this issue, we will try to figure it out, thanks for the help with the APIs
