### ISSUE TITLE
How to delete local copy of the documents 

### ISSUE THREAD

**Issue by rashenoy** [cloudant/CDTDatastore#452]
## Bug Description
Not sure if I would call this a bug per se but more of a task. If there are lots of docs being generated on the device side and you know that once it is pushed to the server there is no use of these documents on the device side. In this setting, you would want to delete the local copy of the document without deleting it on the server side. This will reduce the storage footprint on the local side.  Is there a way to do this ?

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Generate lots of documents. Push the documents to server. Calling delete document will delete the document from server when push is called next time. 

### 2. What you expected to happen
Ability to delete only the local copy (device) copy of the document

### 3. What actually happened
Deleted the documents on the server side

**Comment by mikerhodes** [comment]
It sounds like your scenario might be a simpler problem than CDTDatastore is designed for. 

CDTDatastore is designed around full bi-directional document sync, and is fairly complicated to achieve that as well as having a wire protocol designed around this requirement. The behaviour you describe is a foundational requirement for CDTDatastore (it's syncing the delete to get the server and client databases in sync).

From what you say, you are mostly looking to store documents locally and then upload the to Cloudant later, perhaps when the device is online. After this you don't need the documents locally any more. This is more of a store-and-forward problem than a sync problem.

If this is right, I would take a look at simply caching the documents on the device and then using the normal HTTP APIs for Cloudant to push up the documents via `_bulk_docs`. This has the benefit of being more efficient on the wire and easier to debug.

**Comment by rashenoy** [comment]
Thanks Mike. You are right that if it was a one time thing I would agree that using the HTTP API's for cloud push makes sense. However, this is not just store-and-forward. Before it is finally decided that the doc will no longer be updated there will be multiple revisions that will happen on the doc and these need to be synched. At some point in time the document doesnt need to be updated anymore. After this event, you dont need to keep the local copy anymore. 
e.g. document contains stops on your road trip. It needs to be synched while you are on the road trip. But when the trip finally ends, you will never need it locally.

**Comment by mikerhodes** [comment]
_nods_. 

Unfortunately here I think your only option is separate databases at this point. The sync process is based around essentially bringing two databases completely in sync, so I think you will end up re-creating the documents when you did a pull replication from the server even if we allowed the documents to be scrubbed from the local data store.

**Comment by rashenoy** [comment]
Understand. So if this feature is allowed, it should still be useful when using pushReplication and not pull replication. That's what I have currently in my project.

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
