### ISSUE TITLE
Intermittent 404 received on pull replication 

### ISSUE THREAD

**Issue by paulJordaan** [cloudant/CDTDatastore#454]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description

Intermittently during a pull replication a device would get stuck in a state where it is not able to complete replication to a database because it is receiving a 404 response for a certain sequence. After a lot of digging I came across this [issue](https://github.com/couchbase/couchbase-lite-ios/issues/377) on the [couchbase-lite-ios](https://github.com/couchbase/couchbase-lite-ios) repo which described a similar issue.  

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
This issue is difficult to reproduce as it only occurs intermittently on some devices. I have not been able to recreate the issue in a reliable way.

### 2. What you expected to happen
Expect a replication to complete.

### 3. What actually happened
A replication can get stuck in loop where it continuously errors with "404 Not Found" for a specific sequence when setting `CDTChangeLogLevel(CDTREPLICATION_LOG_CONTEXT, DDLogLevelWarning);`

When searching for the requested sequence id via the web UI the sequence can also not be found.

According to the issue from the above mentioned couchbase repo this can happen "as a race condition if a revision on the server gets replaced by a newer one and then compacted away, before the client receives a notification of the newer revision."

By manually applying the changes in this [pull request](https://github.com/couchbase/couchbase-lite-ios/commit/87f32616d405d00da798a45450c15fa97aa3485c) I was able to get one of my devices experiencing the issue out of the loop. Would it be possible for one of the maintainers to review the changes from the mentioned pull request to see if it might be relevant to this library. I'm not familiar enough with the code and the replication logic to be sure that the mentioned changes is not breaking anything else

## Environment details
- Version(s) that are affected by this issue.
    > 2.1.1
- iOS/macOS version
    > iOS 10.13.1

**Comment by ricellis** [comment]
Interestingly the CouchDB replication protocol doesn't explicitly specify what to do in the case of receiving a `404` for a revision that has been calculated as needing to be fetched.

The [Replicate Changes](http://docs.couchdb.org/en/stable/replication/protocol.html#replicate-changes) flow shows only a `200` response for `Fetch Next Changed Document`.

From [protocol robustness](http://docs.couchdb.org/en/stable/replication/protocol.html#protocol-robustness):
>The Replicator SHOULD NOT count every HTTP request failure as a fatal error. It SHOULD be smart enough to detect timeouts, repeat failed requests, be ready to process incomplete or malformed data and so on

This suggests that re-trying a failed request is in general the preferred course of action, but obviously for the case you describe that isn't going to work as the revision is never going to exist again. It is, however, difficult to distinguish that type of `404` from, say, an eventual consistency `404` where the document does exist, but just not on all the nodes yet.

[Fetch Changed Documents](http://docs.couchdb.org/en/stable/replication/protocol.html#fetch-changed-documents) does make reference to using the `latest=true` parameter to solve race conditions where the document is changed between handling the changes feed and fetching. I suspect this might be what is actually missing from CDT's replicator.

Our replicator follows slightly different paths depending on the availability of the `_bulk_get` endpoint so are you able to elaborate on the version of Apache CouchDB or Cloudant you are replicating with?

**Comment by paulJordaan** [comment]
I'm replicating with a IBM Cloudant service. Version info below.

```
{
  "couchdb": "Welcome",
  "version": "2.1.1",
  "vendor": {
    "name": "IBM Cloudant",
    "version": "7668",
    "variant": "paas"
  },
  "features": [
    "geo",
    "scheduler",
    "iam"
  ],
  "features_flags": [
    "partitioned"
  ]
}
```

**Comment by paulJordaan** [comment]
@ricellis any feedback you could provide on this?

**Comment by ricellis** [comment]
@paulJordaan Sorry, I should have acknowledged the additional information you provided, thank you. We're looking into the problem.

**Comment by smithsz** [comment]
Hi @paulJordaan. We think we've resolved this issue by adding the `latest=true` parameter when pulling revisions. As you say, this edge case is tricky to reproduce but using the debugger I've been able to pause the replication after collecting changes, update a remote document, compact the remote database and then resume without error. Would you be able to take a look at the latest master branch and run the tests you have? It would be much appreciated. Thanks.

**Comment by paulJordaan** [comment]
Hi @smithsz. Sorry for the delay in getting back you on this. We have again hit a scenario where the issue has appeared even with your changes with the `latest=true` flag set. Switch to the branch where  I applied the pull request changes from couchbase-lite repo as mentioned above again got me out of the 404 loop. I would appreciate if you could take a look if the changes from the mentioned pull request will have any adverse effects on the way this lib is working.

**Comment by smithsz** [comment]
Hi Paul. Sorry for the problems. Did this happen on the first pull?
The first pull runs though `pullBulkRevisionsWithAllDocs` (and not `pullBulkRevisionsBulkGet`).
The PR you reference in couchbase-lite has a patch for `pullBulkRevisionsWithAllDocs` to remove missing revisions and avoid retrying the fetch. I think we're missing this piece.
I hope the `latest=true` addition we made has solved the `pullBulkRevisionsBulkGet` case so we don't need that part of the patch. Can you confirm this? Thanks.

**Comment by paulJordaan** [comment]
I will look into it and let you know. As you know it is very difficult replicating the scenario so I've mostly tried to debug when it occurs. Since I've managed to get out of the loop I'm not sure I'll be able to replicate the scenario at the moment but I will see what's possible. Are there any obvious issues that can be introduced by the mentioned PR? I would like to get a possible fix out as soon as possible as I'm not sure how many users are being effected

**Comment by ricellis** [comment]
>Are there any obvious issues that can be introduced by the mentioned PR?

I think the problem we have is knowing that a `404` is permanent. I'm not sure if that code pre-dates the clustering in CouchDB 2.x, but I think there are scenarios where a request directed at the wrong node in a window of eventual consistency could get a _transient_ `404`. IIUC that patch code considers all `404`s _permanent_ and consequently under those circumstances would prevent the rev from ever downloading.

**Comment by paulJordaan** [comment]
@ricellis is it possible for the Cloudant team to take a look at this again? I'm still receiving reports of users being affected by the missing revision loop. Any help would be much appreciated.

**Comment by ricellis** [comment]
We'll take another look at it - I'm still pretty convinced the suggested patch is going to expose some edges for multi-node scenarios with possibly transient `404`s, but if the `latest=true` fix isn't working then there must be another scenario we didn't manage to test so we can try and uncover that.

Did you manage to figure out if this was only happening on the first pull?

**Comment by paulJordaan** [comment]
Thanks for taking another look. I haven't been able to establish if it is only happening on the first pull.

**Comment by ricellis** [comment]
After some further investigation it seems like the 404 log messages might be coming from the device datastore rather than the remote server. Are you able to give us one of the 404 log messages so we can try and correlate that?

Also there are two places where that could happen, one of which is attachment handling. Are you using attachments? Knowing that could help us narrow in a bit.
Thanks.

**Comment by paulJordaan** [comment]
Thanks for the assistance. See log message below.

`2019-06-27 08:28:37.307398+0200 D-Fect[689:247977] CDTReplicator pull, source: https://{connectionstring}/{db}, target: proj_9b0f73b32aa8e7d174182b7b9b2f07c8 filter name: loopback/project, filter parameters {
    projectId = 9b0f73b32aa8e7d174182b7b9b2f07c8;
}, unique replication session ID: repl002 error: Error Domain=TDHTTP Code=404 "404 not_found" UserInfo={NSLocalizedFailureReason=not_found, NSLocalizedDescription=404 not_found}`

To your second question, yes I am using attachments

**Comment by paulJordaan** [comment]
@ricellis have you by any chance been able to look at this issue again?

**Comment by ricellis** [comment]
Yes, I've been going through various paths that might expose a problem like this and I have a test scenario in mind that I'm trying to get up and running.

Do you have a fork where you applied the patch that I could look at? Or when you successfully broke the loop with the patch did you patch both `pullBulkRevisionsWithAllDocs` and `pullBulkRevisionsBulkGet`? Also are you able to ascertain whether the specific deleted sequence you had issues with had attachments prior to the deletion?

**Comment by ricellis** [comment]
Oh one other question too, do you run compaction (`CDTDatastore compactWithError`) on your local datastore as well?

**Comment by paulJordaan** [comment]
Hi, when I successfully broke the look I implemented the patch to both `pullBulkRevisionsWithAllDocs` and `pullBulkRevisionsBulkGet`.

I've not been able to ascertain if the revision had issues with attachments prior to the deletion.

And to you last question, I'm not using `compactWithError` on the local datastore.

**Comment by ricellis** [comment]
I think I understand the scenario now under which this can happen, did you also have warning messages in the log like this?
`no "ok" revision found in _bulk_get response for docid=..., revid=...`

**Comment by paulJordaan** [comment]
I'm not seeing the above message in the error logs.

Logs I'm assuming thats related to the error looks like the following:
`2019-07-15 08:11:41.365192+0200 D-Fect[1015:606310] CDTReplicator pull, source: https://{host}/{db}, target: proj_337d435a26a165b42409779ff1dfa61c filter name: loopback/project, filter parameters {
    projectId = 337d435a26a165b42409779ff1dfa61c;
}, unique replication session ID: repl002 error: Error Domain=TDHTTP Code=404 "404 not_found" UserInfo={NSLocalizedFailureReason=not_found, NSLocalizedDescription=404 not_found}`

and 

`2019-07-15 08:30:18.983992+0200 D-Fect[1038:610041] CDTReplicator pull, source: https://{host}/{db}, target: proj_337d435a26a165b42409779ff1dfa61c filter name: loopback/project, filter parameters {
    projectId = 337d435a26a165b42409779ff1dfa61c;
}, unique replication session ID: repl002 new state: CDTReplicatorStateError (5)`

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
