### ISSUE TITLE
enumerateObjectsUsingBlock is too slow when SQLCipher is used - Performance Issue

### ISSUE THREAD

**Issue by Fenil15** [cloudant/CDTDatastore#456]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description
Iterating query result is taking too much time only when SQL Cipher encryption is enabled.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
I have a CouchDB database which have over 13000 documents synced locally (This is just test data, actual data will go up further). I have added indexing to relevant keys required for querying using `ensureIndexed`. However, when datastore is unencrypted the same query and its iteration takes less than 2 secs but when I change the database to be encrypted its query result takes 2 secs but iterating it over using `enumerateObjectsUsingBlock` takes more than 50secs.

Summing up -
Below command gets executed in less than 2 secs (For both Encrypted and Unencrypted DB)-
> CDTQResultSet* result = [self.datastore find:oQueryDictionary skip:nSkip limit:nLimit fields:arrFields sort:sort];

Below command takes more than 50secs for Encrypted DB and less than 2 secs for Unencrypted DB for same result of ~1000 documents in result 
> [result enumerateObjectsUsingBlock:^(CDTDocumentRevision *rev, NSUInteger idx, BOOL *stop) {
> NSDictionary* oCurrentDict = rev.body;
> }

### 2. What you expected to happen
Expected the response processing time to be less than 2secs

### 3. What actually happened
Result response is taking more than 50secs for Encrypted DB (This time increases with increase in number of documents in response). However, Non-encrypted DB is unaffected by size of documents returned by query result

## Environment details

- Version(s) that are affected by this issue.
    -  ~> 2.1.1
-  iOS/macOS version
    - iPhone 5s, iOS v12.0
- pod library you are using:
    - "CDTDatastore/SQLCipher", '~> 2.1.1'

**Comment by emlaver** [comment]
Hi @Fenil15, could you provide a sample of your xcode app as a zip file or in a Github project? If not, can you provide the values for find, skip, limit, fields, and sort for `CDTQResultSet`? And, can you share the code of your index and one of your documents?

**Comment by Fenil15** [comment]
Hi @emlaver , It's pretty basic query without any operator added -
Index Example - 
```
NSString *ensuredIndex = [self.datastore ensureIndexed:@[@"table_id", @"table_type", @"plugin_id", @"row_seq"] withName:@"cloudantIndex"];
```

Find Call Example -
``` 
NSNumber* nPluginId = [NSNumber numberWithInt:0];
NSString* strTableTypeValue = @"record";
NSDictionary* oQueryDictionary = [[NSDictionary alloc] initWithObjectsAndKeys:strTableTypeValue, @"table_type", nPluginId, @"plugin_id", nil];
CDTQResultSet* result = [self.datastore find:oQueryDictionary skip:0 limit:0 fields:nil sort:nil];
```

**Comment by emlaver** [comment]
@Fenil15 The `CDTQResultSet` result set holds the documents ids from the matching index query (if you have an index).  If there’s no index, it will get all the documents.
The actual reading of the document data happens in the `enumerateObjectsUsingBlock` method.

If your CouchDB database continues to grow and/or you have a large/complex document model, the time to decrypt the data in each document will also increase.
If you want to improve the processing time, I’d recommend tweaking your query to limit the amount of documents returned and reviewing your data model to potentially decrease the document size.

**Comment by Fenil15** [comment]
@emlaver Yes, changing the limit do impact the processing time. Also, As per my understanding of working with SQLCipher, doesn't the encryption and decryption takes place for the entire database and not with Individual tables? Or there is an additional encryption/decryption of each Document's content by this library?

**Comment by ricellis** [comment]
> doesn't the encryption and decryption takes place for the entire database and not with Individual tables?

Yes, the entire database is encrypted, but each page of the database is encrypted separately. Decryption takes place for each page read.

> there is an additional encryption/decryption of each Document's content by this library?

No, but the more documents you read, the more pages will be read (and hence decrypted). If you enumerate 1000 documents you will end up decrypting more pages than if you enumerate 10 documents.

So just to clarify a bit more on what happens here:
1. The call to `find` uses the indexes to find the document IDs that match the query and returns them in a result set.
1. Calling `enumerateObjectsUsingBlock` uses the set of document IDs to read and return each document to the block.

The more and larger the documents that need to be read in part 2 the longer the work is going to take, amplified by the processing overhead of the decryption. It's hard to say without understanding your use case, but returning 1000 documents seems like a lot, given that a user would likely need to page through that many results anyway.

**Comment by Fenil15** [comment]
@ricellis @emlaver Thanks for your input. This helps!
I agree limit of 1000 shouldn't be required for most of the use cases and this delay shouldn't arise for most of the use cases.
Basically, we will be providing the query input and limit to be configurable using an interface, so we don't know yet how it will be consumed. But given the understanding and its impact we can either provide best practices / FAQs / Limit the max query limit.
