### ISSUE TITLE
CocoaPods depenedency

### ISSUE THREAD

**Issue by rashenoy** [cloudant/CDTDatastore#459]
## Bug Description
Currently CDTDatastore is forcing the project to depend on very old version CocoaLumberJack (2.0). That version of CocoaLumberJack only supports swift 2.3. Unable to use CDTDatastore in my current project that has swift 5.0 

### 2. What you expected to happen
Upgrade the dependency to a fairly recent version of CocoaLumberJack as the dependency

### 3. What actually happened
Even if override the version, it will still fail saying CDTDatastore depends on 2.0

  In Podfile:
    CDTDatastore was resolved to 2.1.1, which depends on
      CDTDatastore/standard (= 2.1.1) was resolved to 2.1.1, which depends on
        CDTDatastore/common-dependencies (= 2.1.1) was resolved to 2.1.1, which depends on
          CocoaLumberjack (~> 2.0)

## Environment details
- Latest version of CDTDatastore
- iOS 13.x

**Comment by emlaver** [comment]
@rashenoy thanks for bringing this to our attention! Are you interested in opening a PR for this?

**Comment by emlaver** [comment]
I created a branch and updated `CocoaLumberJack` to 3.6.  Can you try pointing your Podfile to this branch? e.g.
```
pod "CDTDatastore", :git => 'https://github.com/cloudant/CDTDatastore.git', :branch => '459-update-cocoa-lumberjack-dep'
```

**Comment by rashenoy** [comment]
Appreciate you make the snapshot release quickly. I have tried it and now it uses the latest CocoaLumberjack. Please let me know if I need to do anything else. I will use the production release when you make one for the same

**Comment by ricellis** [comment]
Closing as this library is now EOL and this issue won't be fixed here.
The issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
