### ISSUE TITLE
Future support beyond EOL via CDTDatastore forks by the community

### ISSUE THREAD

**Issue by marco-theraforge** [cloudant/CDTDatastore#465]
## Bug Description

We are using CDTDatastore for a platform and we are interested in continuing using it.

This blog page states:

https://blog.cloudant.com/2021/06/30/Cloudant-SDK-Transition.html

There has been some **interest in the Apache CouchDB community** about developing forks of the mobile sync libraries. **We will update this post with more information as it becomes available.**

[...]
Where can I get more help?
Please feel free to open issues on the project GitHub repositories or contact support via your IBM Cloudant dashboard.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

Wanted to showcase the CDTDatastore and Cloudant tech as part of our broad development solution.

### 2. What you expected to happen

Would like to learn more about the aforementioned "interest in the CouchDB community" about developing forks to be able to collaborate. Or would like to get pointers to at least participate in the discussions...

### 3. What actually happened

n/a

## Environment details

n/a

**Comment by ricellis** [comment]
@marco-theraforge thanks for your interest

>Would like to learn more about the aforementioned "interest in the CouchDB community" about developing forks to be able to collaborate. Or would like to get pointers to at least participate in the discussions...

The discussions were in the [CouchDB Slack](https://couchdb.slack.com/archives/C49LEE7NW/p1623225157364400)† - so I think that is the right place participate.

†I believe the message retention in that Slack is limited so I don't know how long that link will remain valid, but the message I'm referring to was from @janl volunteering for iOS.

**Comment by marco-theraforge** [comment]
Thanks, Rich. I have commented on @janl’s message on Slack.

I agree with others that it would make a lot of sense to have CDTDatastore as part of the CouchDB community’s projects.

Marco
